name: CI

on:
  workflow_call

jobs:
  Check:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@main
      
      - uses: KengoTODA/actions-setup-docker-compose@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check docker compose version
        run: docker compose version

      - name: Run lint
        run: |
          ./lint.sh
